### ISSUE TITLE
StaticExecutor bug

### ISSUE THREAD

**Issue by Thurisas** [omp4j/omp4j#4]
omp4j-version: 1.2.
java version: 1.8.0_112
CPU: 6-Core AMD
```
// omp parallel for schedule(static) threadNum(2)
for (int i = 0; i < 100; i++) {
	System.out.println("do something");
}
```
Preprocessed:
```
/* === OMP CONTEXT === */
class OMPContext {
	public MoneyTransfer[] local_transfers;
}
final OMPContext ompContext = new OMPContext();
ompContext.local_transfers = transfers;
final org.omp4j.runtime.IOMPExecutor ompExecutor = new org.omp4j.runtime.StaticExecutor(2);
/* === /OMP CONTEXT === */
for (int i_eKE = 0; i_eKE < ompContext.local_transfers.length; i_eKE++) {	final int i = i_eKE;
	ompExecutor.execute(new Runnable(){
		@Override
		public void run() {
			ompContext.local_transfers[i].execute();
			}});
}ompExecutor.waitForExecution();
```
Throws Exception for 1-3 threads:
```
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
        at java.util.ArrayList.rangeCheck(ArrayList.java:653)
        at java.util.ArrayList.get(ArrayList.java:429)
        at org.omp4j.runtime.StaticExecutor.execute(StaticExecutor.java:65)
```
No errors occur using a thread number greater than 3 or the dynamic scheduling.

**Comment by petrbel** [comment]
Hi @Thurisas and welcome. Would you mind creating a _minimal not-working example_? By that I mean a `.java` file that can(not) be preprocessed. Thank you.

Btw what is your motivation for using static scheduling? The dynamic one is pretty well optimized in Java8.

**Comment by Thurisas** [comment]
[Main.txt](https://github.com/omp4j/omp4j/files/685108/Main.txt)
[Main_preprocessed.txt](https://github.com/omp4j/omp4j/files/685061/Main.txt)

Attached them as .txt . There is no issue on preprocessing the file, but on execution with less than 4 threads.

My motivation is some performance research on different approaches. I need to distribute some generated workload on different ways.
